- "https://adaway.org/hosts.txt"
- "https://filters.adavoid.org/ultimate-ad-filter.txt"
- "https://filters.adavoid.org/ultimate-privacy-filter.txt"
- "https://filters.adavoid.org/ultimate-security-filter.txt"
- "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt"
# ...（中间是你提供的所有链接）
- "https://raw.githubusercontent.com/REIJI007/Adblock-Rule-Collection/main/Whitelist.txt"
